use_frameworks!

target 'SDWebImageFLIFCoder_Example' do
  platform :ios, '8.0'
  pod 'SDWebImageFLIFCoder', :path => '../'

  target 'SDWebImageFLIFCoder_Tests' do
    inherit! :search_paths

    
  end
end

target 'SDWebImageFLIFCoderExample-macOS' do
  platform :osx, '10.10'
  pod 'SDWebImageFLIFCoder', :path => '../'
end