use_frameworks!

target 'SDWebImageFLIFCoder_Example' do
  platform :ios, '9.0'
  pod 'SDWebImageFLIFCoder', :path => '../'

  target 'SDWebImageFLIFCoder_Tests' do
    inherit! :search_paths

    
  end
end

target 'SDWebImageFLIFCoderExample-macOS' do
  platform :osx, '10.11'
  pod 'SDWebImageFLIFCoder', :path => '../'
end