//
//  SDImageFLIFCoder.h
//  SDWebImageFLIFCoder
//
//  Created by lizhuoli on 2019/1/30.
//

#import <SDWebImage/SDWebImage.h>

NS_ASSUME_NONNULL_BEGIN

static const SDImageFormat SDImageFormatFLIF = 14;

@interface SDImageFLIFCoder : NSObject <SDProgressiveImageCoder>

@property (nonatomic, class, readonly, nonnull) SDImageFLIFCoder *sharedCoder;

/**
 This is a option used by FLIF encoding. Due to the compatible issue of animated FLIF images generated by old version flif codec (before v0.3) .
 If you want to keep backword compatibility, enable this option. The default value is NO.
 */
@property (nonatomic, assign) BOOL disableColorBuckets;

@end

NS_ASSUME_NONNULL_END
